adb:
  server:
    host: 127.0.0.1
    port: 5037
  device_serial: 10.1.1.60:6666

uninstall: True
install: True
wait_for_download: True

timeouts:
  detect_credit_screen: 300
  detect_setup_screen: 300
  gakuen_running: 300
  download_start: 300
  download_finish: 600